name: Sp2N_mixed_representation_singlets_2405.05765
channels:
  - defaults
  - conda-forge
dependencies:
  - arpack=3.8.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - curl=8.8.0
  - git=2.45.1
  - gmp=6.3.0
  - icu=73.2
  - julia=1.10.3
  - krb5=1.21.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libopenblas-ilp64=0.3.27
  - libopenlibm4=0.8.1
  - libosxunwind=0.0.6
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libutf8proc=2.8.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=18.1.5
  - metis=5.1.1
  - mpfr=4.2.1
  - ncurses=6.5
  - openblas-ilp64=0.3.27
  - openlibm=0.8.1
  - openssl=3.3.0
  - p7zip=16.02
  - pcre2=10.43
  - perl=5.32.1
  - pip=24.0
  - python=3.10.14
  - readline=8.2
  - setuptools=70.0.0
  - suitesparse=5.10.1
  - tbb=2021.12.0
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - corrfitter==8.2
      - gvar==11.11.17
      - h5py==3.10.0
      - lsqfit==13.0.3
      - numpy==1.26.1
      - scipy==1.13.1
